language: node_js
node_js:
- node
script:
- yarn build
deploy:
  provider: firebase
  token:
env:
  global:
    secure: IsTEhZfxjimW+eFASZPfmh/WMlwRWTZXiE0lMg5H0RQYxtIrqxVqi57sPNJ4ZPtWNotKDJUujO1ilG4CNI2pBzjM1hnxbEgF5zbfkjtwVeTAXaz9xnO0BLtGaavF3vCMPvy7dORMPqXTQ0tOM+CPzV/wLTiwObyXAd675rKhxOsZMeUQoXGxLJnfLo1V+WMFKEMjbd5DZM4+vRFEy387g3PX30ixS/Ul0xQ45cCAgu7PGTs9QXhP+BpH4BWpipus8v50ayKhPXBvDtsHbUIHC5FqQ7AxG0YVWQ4/Is3SutZak1Gx3MFgVBDQHAVE2g/q84Xw6wM/mVqd3KRdrL4jE4cwOqkg3Bu/gkWcGqYLIC80hOCyVG1kO0wQKtnBNFQLRa6Oqsj/as8vJ/UY/MsqooYbkgiwBREEi+z3l33xKlTYB4Vql4UAv+7ne66scbJVbCbmR0vkLY9DRcQv9SgkXJW5gazbE0z+sPOOZYe4gzsNMxV+TAooBC+wf1Ixb61LE7Nr9NDqTbVPJVkzZa4IHxXYhyshTv+tmjwU4Tpund+aRX3THhubOVVSSnpRdYr4JezfD9W5C47p0+c3IUEPAhiGMEd8bYfk6wSSbvOJ0JSsB37ygB6k1MFyq1MjuQ+v9xrPzSRj2x6JRk0BshCoivryxS1SuUP50VJ0ymzFDVk=
